name: Actions on Heltai
on: [push]
jobs:
  test-docker-image:
    runs-on: ubuntu-latest
    container: heltai/example-image

    steps:
     - name: Check out repository
       uses: actions/checkout@v3
     - name: Check that we have vim installed
       run: test -f /bin/vim && echo "Vim is installed"