name: Actions on Rigo
on: [push]
jobs:
  test-docker-image:
    runs-on: ubuntu-latest
    container: ghcr.io/maurorigo/jaxubuntu:latest

    steps:
     - name: Checkout the repo
       uses: actions/checkout@v3
     - name: Check that we have vim installed
       run: test -f /bin/vim && echo "Vim is installed"
     - name: Run tests in tests/heltai directory
       run: |
          cd tests/rigo
          python3 test.py
